app.constant "BromeliadHelp",
    'habitat': "The “Dataset-Visit habitat (Date)” field should autofill. O campo “Dataset-Visit Habitat (Date)” será preenchido automaticamente."
    'date': "The actual bromeliad, not the whole field season.  Data da coleta da Bromélia em questão, não a data de início da visita."
    'original_id': "This should exactly match your field notes, do not change bromeliad identifiers. Deve ser usado a identificação da bromélia feita em campo, não altere as identificações."
    'species': "Please ensure this is spelt correctly. If genus only identification, use this form: genus sp.”  Assegure-se que o nome da espécie esteja escrito corretamente. Se a única identificação for o gênero, usar o formato “gênero sp.”"
    'water': "Actual: Volume of water present in the bromeliad (ml). Volume de água presente na bromélia (ml). Max: Maximum water volume bromeliad can held (ml). Volume máximo de água que a bromélia pode reter (ml)"
    'height': "Height above ground: enter 0 if the bromeliad was growing on the ground, a positive number if epiphytic bromeliad, leave as NA if data missing. Altura acima do solo: 0 se a bromélia estiver crescendo no chão; número positivo se for uma bromélia epífita; NA se não tiver esse dado."
    'diameter': "Horizontal distance from one side of the plant to the other (cm). Distância horizontal de uma extremidade a outra da pl)ncia horizontal de uma extremidade a outra da planta, com as folhas extendidas manualmente a sua máxima extensão.anta (cm)."
    'extended_diameter': "This is the horizontal distance from one side of the plant to the other, with the leaves pulled by hand to their maximal extent. Distância horizontal de uma extremidade a outra da planta, com as folhas extendidas manualmente a sua máxima extensão."
    'leaf_width': "Width across the middle bromeliad leaf, taken at the leaf base. Largura da folha do meio da bromélia, medida na base da folha."
    'num_leaf': "The number of water-holding leaves. Número de folhas capazes de reter água."
    'longest_leaf': "The length of the longest bromeliad leaf, from its base to its tip. Comprimento da maior folha da bromélia, da base até a ponta."
    'attribute': "Extra information, for example: ant nest, spider presence. Informações extra, por exemplo: ninho de formiga, presença de aranhas."
    'value': "In general: present or absent. Em geral: presente ou ausente."
    'add_attribute': "Add more extra information. Adicionar mais informações extra."
    'detritus_dry_mass': "To insert detritus information. Para inserir informação sobre detrito."
    'detritus_min': "Size of particulate, the lower bound of the sieve. Tamanho do particulado, limite inferior da peneira."
    'detritus_max': "Size of particulate, the upper bound of the sieve. Tamanho do particulado, limite superior da peneira."
    'detritus_mass': "Dry mass of detritus in g. Massa seca de detrito em g."
